before_install: 
- docker pull opensuse/tumbleweed # Use opensuse Tumbleweed as test
- docker run -d -p 127.0.0.1:80:4567 opensuse/tumbleweed /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run opensuse/tumbleweed /bin/sh -c "cd /root/sinatra; bundle exec rake test"



sudo: required
language: bash
services:
  - docker

script:
    - ./test/libs/bats/bin/bats test.bats
