#+TITLE: Configs & Dotfiles
#+AUTHOR: Vishakh Kumar
#+EMAIL: vishakhpradeepkumar@gmail.com
#+LICENSE: GPLv3
#+LANGUAGE: en
#+OPTIONS: num:5 whn:2 toc:4 H:6

#+COLUMNS: %25ITEM %TODO %3PRIORITY %TAGS


:padline no

* Overview

Built these configuration files because I spend way too much time on my computer and I like my computer a certain way.
Also, I reinstall the os from time to time to clear up junk (hopefully the number of times I do this in the future will go down, as I'm using opensuse.)


1) Command-line tools 
   1) Install command_line_tools.txt
      #+BEGIN_SRC bash
      zypper install <<command_line_tools>>
      #+END_SRC
   2) Place configuration files for commandline tools
      #+BEGIN_SRC bash

      #+END_SRC
2) GUI pplications
   1) Install gui_tools.txt
      #+BEGIN_SRC bash
      zypper install <<gui_tools>>
      #+END_SRC
   2) Place configuration files for applications
      #+BEGIN_SRC bash

      #+END_SRC
3) Modify system preferences
4) Modify personal preferences
5) Add cloud services

* File management

- org-agenda integration
#+BEGIN_SRC emacs-lisp
(setq org-agenda-files
    (file-expand-wildcards "~/Proposals/*.org")
    (file-expand-wildcards "~/Projects/*.org")
    (file-expand-wildcards "~/PersonalDevelopment/*.org")
    (file-expand-wildcards "~/College/*.org")
    (file-expand-wildcards "~/Business/*.org")
    (file-expand-wildcards "~/Finances/*.org")
)
#+END_SRC emacs-lisp


** organizer.org
*** Tasks
  :PROPERTIES:
  :CATEGORY: Task
  :END:
*** Important dates
  :PROPERTIES:
  :CATEGORY: Date
  :END:
**** Anniversary
**** Expiry Date of Credit Cards
Inform one week in advance
**** Bills to be paid
**** Membership days
**** Religious Holiday
**** Government Holiday
**** Conference Periods
**** College Events

** refile.org
Main org file for org-capture and todo tasks
** Proposals
For all the evil plans you have for the future.
*** commercial_ideas.org
*** whimsical_ideas.org
*** proposals.org
*** Subfolder 1
** Configuration
All your config files are to be stored here
*** config.org
For all your configuration file definitions
*** emacs_configuration.org
*** projectManagement.org
*** secrets.org
For account information and ssh keys.
** Archive
For archived documents that don't quite have a home but can't be deleted
*** archive.org
Archived sub trees
** Website :website:
*** website.org
For website source code
*** blog.org
Topic index for my blog

** Personal Development
*** online_learning.org
For all your online learning todos and planning
**** lynda
**** mit ocw
**** coursera
*** improvements.org
** College
*** college.org
All class information and deadlines. Treat as read-only during semester unless the professor gives test details during the semester.
*** Current Semester
**** Class 1
***** notes.org
***** textbook.pdf
***** Office Lens Scans
Not just Office Lens Scans but all scans in general. Just going to use Office Lens a lot.
Treat this folder as read only - don't delete anything.
***** Old Papers
**** Class 2
***** notes.org
***** textbook.pdf
***** Office Lens Scans
***** Old Papers
*** Previous semesters
** Business
*** business.org

**** System Maintenance
  :PROPERTIES:
  :CATEGORY: Maintenance
  :END:
**** Payroll
  :PROPERTIES:
  :CATEGORY: Payroll
  :END:
**** Accounting
  :PROPERTIES:
  :CATEGORY: Accounting
  :END:
**** Finances
  :PROPERTIES:
  :CATEGORY: Finance
  :END:
**** Hardware Maintenance
  :PROPERTIES:
  :CATEGORY: Hardware
  :END:
**** Tasks
  :PROPERTIES:
  :CATEGORY: Task
  :END:
**** Research and Development
  :PROPERTIES:
  :CATEGORY: Idea
  :END:
**** Notes
  :PROPERTIES:
  :CATEGORY: Note
  :END:
**** Purchase Order Tracking
  :PROPERTIES:
  :CATEGORY: PurchaseOrder
  :END:
**** Passwords
  :PROPERTIES:
  :CATEGORY: Password
  :END:
**** Clients & Associates
  :PROPERTIES:
  :CATEGORY: Contact
  :END:
**** Procedures
  :PROPERTIES:
  :CATEGORY: Workflow
  :END:
**** Checklists
  :PROPERTIES:
  :CATEGORY: Checklist
  :END:


**** COMMENT Stolen from somewhere
Business-related information and plans
- Clients
- Procedures
- Associates
- Media
- Checklists
- Work-in-progress

**** COMMENT Stolen from http://doc.norang.ca/org-mode.html#OrgFileStructure 
***** System Maintenance
***** Payroll
***** Accounting
***** Finances
***** Hardware Maintenance
***** Tasks
***** Research and Development
***** Notes
***** Purchase Order Tracking
***** Passwords

*** contacts.org
** Finances
*** Banks
  :PROPERTIES:
  :CATEGORY: Bank
  :END:
**** Account 1 - Bank 1
***** Account Number
***** Billing Address

*** Money
  :PROPERTIES:
  :CATEGORY: Money
  :END:
**** Archive
** Medical
*** medical.org for context and information
**** NMC Deira
**** NIMHANS
**** Medical Archive

** Asset Management
Need more advice here
*** Real Estate
Not exactly applicable now but should be in the future.
*** Vehicles
Not a concern now but will be in the future.
*** Warranties
Should keep scans of the warranty sticker
*** Electronics
*** Home Inventory
Mainly the fancier ones that require upkeep.
** Photos
Organized by trip.
** Documents
*** Passport 
*** ID
**** Emirates ID
**** Aadhar Card
**** Buzzcard
**** Driver's License
***** Dubai
***** United States

*** CV
Don't delete them anymore. Sort by year
*** Georgia Tech
*** US Admission
*** Medical
*** Digital Files
*** Misc Files
*** US Admission
*** CBSE - JEE
*** IIST
*** MIT
*** Music
*** National Olympiads
*** Organic Charts
*** Physics Project
*** Pictures
*** Plancess Demo CD
*** Ridge View
*** Travel Doc - Reservations
*** US
*** Vijaygiri
*** Vish
*** Vish - Digital Files + Photos
*** Vishakh's Essays

* To use

add to new project template http://blog.modelworks.ch/using-org-mode-to-keep-track-of-your-project-files/

special task category WAIT where you wait for input from someone

http://blog.modelworks.ch/removing-extra-blank-lines-in-emacs/ add hook after saving

org-sparse-tree to find all headlines with a certain tag.

There was a guy out there who described in painstaking detail each step he had to take to remake his configuration. Do that - especially for chrome and firefox extensions.

* Programming Languages
** Python configuration

 (Slightly edited from [[https://medium.com/@henriquebastos/the-definitive-guide-to-setup-my-python-workspace-628d68552e14][Medium Link]]. Credit to Henrique Bastos)

 Requirements: 
 + I need to be able to use multiple versions of CPython 2 and 3, as well as other interpreters like PyPy and Anaconda;
 + Python3 must be the default for everything. However, I should be able to use Python 2 when I wish to.
 + Jupyter Notebook should work with Python2 and Python3, and is able to detect the active virtualenv at jupyter notebook execution time.
 + A single iPython Console for Python3 and one iPython Console for Python2, so no need to install iPython on my projects' virtualenvs.
 + I want useful programs written in Python (ex: youtube-dl) globally available on my system without contaminating the global interpreters and avoiding any library version issues.
 + I want to use virtualenvwrapper to develop my projects allowing me to change context/project quickly with one command.
 + I want this setup to be maintainable without adding too many thing to PATH.

*** Why I use pyenv
 For me pyenv is the best way to install Python on a Mac or Linux. Everything gets installed under your home directoy, without tampering with the rest of the system. Besides that, it supports many different Python implementation such as PyPy, Anaconda, CPython, etc. All with one command.

 #+NAME: command_line_tools
 #+BEGIN_SRC txt
 pyenv
 pyenv-virtualenv
 pyenv-virtualenvwrapper
 #+END_SRC

